package org.bouncycastle.pqc.crypto.gemss;

import androidx.constraintlayout.core.motion.utils.TypedValues;
import androidx.core.view.InputDeviceCompat;
import java.util.HashMap;
import java.util.Map;
import org.bouncycastle.util.Integers;
import org.bouncycastle.util.Pack;
import org.videolan.libvlc.MediaDiscoverer;
import org.videolan.libvlc.MediaPlayer;
import org.videolan.libvlc.RendererDiscoverer;
import org.videolan.libvlc.interfaces.IMediaList;

public class GeMSSParameters {
    public static final GeMSSParameters bluegemss128;
    public static final GeMSSParameters bluegemss192;
    public static final GeMSSParameters bluegemss256;
    private static final Integer bluegemss_128;
    private static final Integer bluegemss_192;
    private static final Integer bluegemss_256;
    public static final GeMSSParameters cyangemss128;
    public static final GeMSSParameters cyangemss192;
    public static final GeMSSParameters cyangemss256;
    private static final Integer cyangemss_128;
    private static final Integer cyangemss_192;
    private static final Integer cyangemss_256;
    public static final GeMSSParameters dualmodems128;
    public static final GeMSSParameters dualmodems192;
    public static final GeMSSParameters dualmodems256;
    private static final Integer dualmodems_128;
    private static final Integer dualmodems_192;
    private static final Integer dualmodems_256;
    public static final GeMSSParameters fgemss128;
    public static final GeMSSParameters fgemss192;
    public static final GeMSSParameters fgemss256;
    private static final Integer fgemss_128;
    private static final Integer fgemss_192;
    private static final Integer fgemss_256;
    public static final GeMSSParameters gemss128;
    public static final GeMSSParameters gemss192;
    public static final GeMSSParameters gemss256;
    private static final Integer gemss_128;
    private static final Integer gemss_192;
    private static final Integer gemss_256;
    public static final GeMSSParameters magentagemss128;
    public static final GeMSSParameters magentagemss192;
    public static final GeMSSParameters magentagemss256;
    private static final Integer magentagemss_128;
    private static final Integer magentagemss_192;
    private static final Integer magentagemss_256;
    private static final Map<Integer, GeMSSParameters> oidToParams;
    private static final Map<GeMSSParameters, Integer> paramsToOid;
    public static final GeMSSParameters redgemss128;
    public static final GeMSSParameters redgemss192;
    public static final GeMSSParameters redgemss256;
    private static final Integer redgemss_128;
    private static final Integer redgemss_192;
    private static final Integer redgemss_256;
    public static final GeMSSParameters whitegemss128;
    public static final GeMSSParameters whitegemss192;
    public static final GeMSSParameters whitegemss256;
    private static final Integer whitegemss_128;
    private static final Integer whitegemss_192;
    private static final Integer whitegemss_256;
    private final GeMSSEngine engine;
    private final String name;

    static {
        GeMSSParameters geMSSParameters = new GeMSSParameters("gemss128", 128, 174, 12, 12, 4, InputDeviceCompat.SOURCE_DPAD, 9, 0);
        gemss128 = geMSSParameters;
        GeMSSParameters geMSSParameters2 = new GeMSSParameters("gemss192", 192, MediaPlayer.Event.EndReached, 20, 22, 4, InputDeviceCompat.SOURCE_DPAD, 9, 0);
        gemss192 = geMSSParameters2;
        GeMSSParameters geMSSParameters3 = new GeMSSParameters("gemss256", 256, 354, 33, 30, 4, InputDeviceCompat.SOURCE_DPAD, 9, 0);
        gemss256 = geMSSParameters3;
        GeMSSParameters geMSSParameters4 = new GeMSSParameters("bluegemss128", 128, 175, 14, 13, 4, 129, 7, 0);
        bluegemss128 = geMSSParameters4;
        GeMSSParameters geMSSParameters5 = new GeMSSParameters("bluegemss192", 192, MediaPlayer.Event.EndReached, 23, 22, 4, 129, 7, 0);
        bluegemss192 = geMSSParameters5;
        GeMSSParameters geMSSParameters6 = new GeMSSParameters("bluegemss256", 256, 358, 32, 34, 4, 129, 7, 0);
        bluegemss256 = geMSSParameters6;
        GeMSSParameters geMSSParameters7 = new GeMSSParameters("redgemss128", 128, 177, 15, 15, 4, 17, 4, 0);
        redgemss128 = geMSSParameters7;
        GeMSSParameters geMSSParameters8 = new GeMSSParameters("redgemss192", 192, MediaPlayer.Event.EncounteredError, 25, 23, 4, 17, 4, 0);
        redgemss192 = geMSSParameters8;
        GeMSSParameters geMSSParameters9 = new GeMSSParameters("redgemss256", 256, 358, 35, 34, 4, 17, 4, 0);
        redgemss256 = geMSSParameters9;
        GeMSSParameters geMSSParameters10 = new GeMSSParameters("whitegemss128", 128, 175, 12, 12, 3, InputDeviceCompat.SOURCE_DPAD, 9, 0);
        whitegemss128 = geMSSParameters10;
        GeMSSParameters geMSSParameters11 = new GeMSSParameters("whitegemss192", 192, MediaPlayer.Event.PositionChanged, 21, 21, 3, InputDeviceCompat.SOURCE_DPAD, 9, 0);
        whitegemss192 = geMSSParameters11;
        GeMSSParameters geMSSParameters12 = r11;
        GeMSSParameters geMSSParameters13 = new GeMSSParameters("whitegemss256", 256, 364, 29, 31, 3, InputDeviceCompat.SOURCE_DPAD, 9, 0);
        whitegemss256 = geMSSParameters12;
        GeMSSParameters geMSSParameters14 = r12;
        GeMSSParameters geMSSParameters15 = new GeMSSParameters("cyangemss128", 128, 177, 13, 14, 3, 129, 7, 0);
        cyangemss128 = geMSSParameters14;
        GeMSSParameters geMSSParameters16 = r13;
        GeMSSParameters geMSSParameters17 = new GeMSSParameters("cyangemss192", 192, 270, 22, 23, 3, 129, 7, 0);
        cyangemss192 = geMSSParameters16;
        GeMSSParameters geMSSParameters18 = new GeMSSParameters("cyangemss256", 256, 364, 32, 31, 3, 129, 7, 0);
        cyangemss256 = geMSSParameters18;
        GeMSSParameters geMSSParameters19 = geMSSParameters18;
        GeMSSParameters geMSSParameters20 = r14;
        GeMSSParameters geMSSParameters21 = new GeMSSParameters("magentagemss128", 128, 178, 15, 15, 3, 17, 4, 0);
        magentagemss128 = geMSSParameters20;
        GeMSSParameters geMSSParameters22 = new GeMSSParameters("magentagemss192", 192, 271, 24, 24, 3, 17, 4, 0);
        magentagemss192 = geMSSParameters22;
        GeMSSParameters geMSSParameters23 = r15;
        GeMSSParameters geMSSParameters24 = new GeMSSParameters("magentagemss256", 256, 366, 33, 33, 3, 17, 4, 0);
        magentagemss256 = geMSSParameters24;
        GeMSSParameters geMSSParameters25 = new GeMSSParameters("fgemss128", 128, MediaPlayer.Event.EncounteredError, 11, 10, 1, 129, 7, 0);
        fgemss128 = geMSSParameters25;
        GeMSSParameters geMSSParameters26 = geMSSParameters25;
        GeMSSParameters geMSSParameters27 = new GeMSSParameters("fgemss192", 192, TypedValues.CycleType.TYPE_VISIBILITY, 18, 18, 1, 640, 9, 7);
        fgemss192 = geMSSParameters27;
        GeMSSParameters geMSSParameters28 = geMSSParameters27;
        GeMSSParameters geMSSParameters29 = new GeMSSParameters("fgemss256", 256, 537, 26, 25, 1, 1152, 10, 7);
        fgemss256 = geMSSParameters29;
        GeMSSParameters geMSSParameters30 = geMSSParameters29;
        GeMSSParameters geMSSParameters31 = new GeMSSParameters("dualmodems128", 128, MediaPlayer.Event.EncounteredError, 11, 10, 1, 129, 7, 0);
        dualmodems128 = geMSSParameters31;
        GeMSSParameters geMSSParameters32 = geMSSParameters31;
        GeMSSParameters geMSSParameters33 = new GeMSSParameters("dualmodems192", 192, TypedValues.CycleType.TYPE_VISIBILITY, 18, 18, 1, 129, 7, 0);
        dualmodems192 = geMSSParameters33;
        GeMSSParameters geMSSParameters34 = geMSSParameters33;
        GeMSSParameters geMSSParameters35 = new GeMSSParameters("dualmodems256", 256, 544, 32, 32, 1, 129, 7, 0);
        dualmodems256 = geMSSParameters35;
        GeMSSParameters geMSSParameters36 = geMSSParameters35;
        Integer valueOf = Integers.valueOf(257);
        gemss_128 = valueOf;
        GeMSSParameters geMSSParameters37 = geMSSParameters22;
        Integer valueOf2 = Integers.valueOf(MediaPlayer.Event.Opening);
        gemss_192 = valueOf2;
        GeMSSParameters geMSSParameters38 = geMSSParameters20;
        Integer valueOf3 = Integers.valueOf(MediaPlayer.Event.Buffering);
        gemss_256 = valueOf3;
        GeMSSParameters geMSSParameters39 = geMSSParameters16;
        Integer valueOf4 = Integers.valueOf(InputDeviceCompat.SOURCE_DPAD);
        bluegemss_128 = valueOf4;
        Integer valueOf5 = Integers.valueOf(IMediaList.Event.ItemDeleted);
        bluegemss_192 = valueOf5;
        GeMSSParameters geMSSParameters40 = geMSSParameters11;
        Integer valueOf6 = Integers.valueOf(515);
        bluegemss_256 = valueOf6;
        Integer valueOf7 = Integers.valueOf(769);
        redgemss_128 = valueOf7;
        GeMSSParameters geMSSParameters41 = geMSSParameters9;
        Integer valueOf8 = Integers.valueOf(770);
        redgemss_192 = valueOf8;
        Integer valueOf9 = Integers.valueOf(771);
        redgemss_256 = valueOf9;
        Integer num = valueOf9;
        Integer valueOf10 = Integers.valueOf(InputDeviceCompat.SOURCE_GAMEPAD);
        whitegemss_128 = valueOf10;
        Integer num2 = valueOf10;
        Integer valueOf11 = Integers.valueOf(1026);
        whitegemss_192 = valueOf11;
        Integer num3 = valueOf11;
        Integer valueOf12 = Integers.valueOf(1027);
        whitegemss_256 = valueOf12;
        Integer num4 = valueOf12;
        Integer valueOf13 = Integers.valueOf(MediaDiscoverer.Event.Ended);
        cyangemss_128 = valueOf13;
        Integer num5 = valueOf13;
        Integer valueOf14 = Integers.valueOf(RendererDiscoverer.Event.ItemAdded);
        cyangemss_192 = valueOf14;
        Integer num6 = valueOf14;
        Integer valueOf15 = Integers.valueOf(RendererDiscoverer.Event.ItemDeleted);
        cyangemss_256 = valueOf15;
        Integer num7 = valueOf15;
        Integer valueOf16 = Integers.valueOf(1537);
        magentagemss_128 = valueOf16;
        Integer num8 = valueOf16;
        Integer valueOf17 = Integers.valueOf(1538);
        magentagemss_192 = valueOf17;
        Integer num9 = valueOf17;
        Integer valueOf18 = Integers.valueOf(1539);
        magentagemss_256 = valueOf18;
        Integer num10 = valueOf18;
        Integer valueOf19 = Integers.valueOf(1793);
        fgemss_128 = valueOf19;
        Integer num11 = valueOf19;
        Integer valueOf20 = Integers.valueOf(1794);
        fgemss_192 = valueOf20;
        Integer num12 = valueOf20;
        Integer valueOf21 = Integers.valueOf(1795);
        fgemss_256 = valueOf21;
        Integer num13 = valueOf21;
        Integer valueOf22 = Integers.valueOf(2049);
        dualmodems_128 = valueOf22;
        Integer num14 = valueOf22;
        Integer valueOf23 = Integers.valueOf(2050);
        dualmodems_192 = valueOf23;
        Integer num15 = valueOf23;
        Integer valueOf24 = Integers.valueOf(2051);
        dualmodems_256 = valueOf24;
        Integer num16 = valueOf24;
        HashMap hashMap = new HashMap();
        oidToParams = hashMap;
        Integer num17 = valueOf8;
        HashMap hashMap2 = new HashMap();
        paramsToOid = hashMap2;
        hashMap.put(valueOf, geMSSParameters);
        hashMap.put(valueOf2, geMSSParameters2);
        hashMap.put(valueOf3, geMSSParameters3);
        hashMap.put(valueOf4, geMSSParameters4);
        hashMap.put(valueOf5, geMSSParameters5);
        hashMap.put(valueOf6, geMSSParameters6);
        hashMap.put(valueOf7, geMSSParameters7);
        GeMSSParameters geMSSParameters42 = geMSSParameters7;
        GeMSSParameters geMSSParameters43 = geMSSParameters8;
        Integer num18 = valueOf7;
        Integer num19 = num17;
        hashMap.put(num19, geMSSParameters43);
        GeMSSParameters geMSSParameters44 = geMSSParameters43;
        GeMSSParameters geMSSParameters45 = geMSSParameters41;
        Integer num20 = num19;
        Integer num21 = num;
        hashMap.put(num21, geMSSParameters45);
        GeMSSParameters geMSSParameters46 = geMSSParameters45;
        GeMSSParameters geMSSParameters47 = geMSSParameters10;
        Integer num22 = num21;
        Integer num23 = num2;
        hashMap.put(num23, geMSSParameters47);
        GeMSSParameters geMSSParameters48 = geMSSParameters47;
        GeMSSParameters geMSSParameters49 = geMSSParameters40;
        Integer num24 = num23;
        Integer num25 = num3;
        hashMap.put(num25, geMSSParameters49);
        GeMSSParameters geMSSParameters50 = geMSSParameters49;
        GeMSSParameters geMSSParameters51 = geMSSParameters12;
        Integer num26 = num25;
        Integer num27 = num4;
        hashMap.put(num27, geMSSParameters51);
        GeMSSParameters geMSSParameters52 = geMSSParameters51;
        GeMSSParameters geMSSParameters53 = geMSSParameters14;
        Integer num28 = num27;
        Integer num29 = num5;
        hashMap.put(num29, geMSSParameters53);
        GeMSSParameters geMSSParameters54 = geMSSParameters53;
        GeMSSParameters geMSSParameters55 = geMSSParameters39;
        Integer num30 = num29;
        Integer num31 = num6;
        hashMap.put(num31, geMSSParameters55);
        GeMSSParameters geMSSParameters56 = geMSSParameters55;
        GeMSSParameters geMSSParameters57 = geMSSParameters19;
        Integer num32 = num31;
        Integer num33 = num7;
        hashMap.put(num33, geMSSParameters57);
        GeMSSParameters geMSSParameters58 = geMSSParameters57;
        GeMSSParameters geMSSParameters59 = geMSSParameters38;
        Integer num34 = num33;
        Integer num35 = num8;
        hashMap.put(num35, geMSSParameters59);
        GeMSSParameters geMSSParameters60 = geMSSParameters59;
        GeMSSParameters geMSSParameters61 = geMSSParameters37;
        Integer num36 = num35;
        Integer num37 = num9;
        hashMap.put(num37, geMSSParameters61);
        GeMSSParameters geMSSParameters62 = geMSSParameters61;
        GeMSSParameters geMSSParameters63 = geMSSParameters23;
        Integer num38 = num37;
        Integer num39 = num10;
        hashMap.put(num39, geMSSParameters63);
        GeMSSParameters geMSSParameters64 = geMSSParameters63;
        GeMSSParameters geMSSParameters65 = geMSSParameters26;
        Integer num40 = num39;
        Integer num41 = num11;
        hashMap.put(num41, geMSSParameters65);
        GeMSSParameters geMSSParameters66 = geMSSParameters65;
        GeMSSParameters geMSSParameters67 = geMSSParameters28;
        Integer num42 = num41;
        Integer num43 = num12;
        hashMap.put(num43, geMSSParameters67);
        GeMSSParameters geMSSParameters68 = geMSSParameters67;
        GeMSSParameters geMSSParameters69 = geMSSParameters30;
        Integer num44 = num43;
        Integer num45 = num13;
        hashMap.put(num45, geMSSParameters69);
        GeMSSParameters geMSSParameters70 = geMSSParameters69;
        GeMSSParameters geMSSParameters71 = geMSSParameters32;
        Integer num46 = num45;
        Integer num47 = num14;
        hashMap.put(num47, geMSSParameters71);
        GeMSSParameters geMSSParameters72 = geMSSParameters71;
        GeMSSParameters geMSSParameters73 = geMSSParameters34;
        Integer num48 = num47;
        Integer num49 = num15;
        hashMap.put(num49, geMSSParameters73);
        GeMSSParameters geMSSParameters74 = geMSSParameters73;
        GeMSSParameters geMSSParameters75 = geMSSParameters36;
        Integer num50 = num16;
        Integer num51 = num49;
        Integer num52 = num50;
        hashMap.put(num52, geMSSParameters75);
        hashMap2.put(geMSSParameters, valueOf);
        hashMap2.put(geMSSParameters2, valueOf2);
        hashMap2.put(geMSSParameters3, valueOf3);
        hashMap2.put(geMSSParameters4, valueOf4);
        hashMap2.put(geMSSParameters5, valueOf5);
        hashMap2.put(geMSSParameters6, valueOf6);
        hashMap2.put(geMSSParameters42, num18);
        hashMap2.put(geMSSParameters44, num20);
        hashMap2.put(geMSSParameters46, num22);
        hashMap2.put(geMSSParameters48, num24);
        hashMap2.put(geMSSParameters50, num26);
        hashMap2.put(geMSSParameters52, num28);
        hashMap2.put(geMSSParameters54, num30);
        hashMap2.put(geMSSParameters56, num32);
        hashMap2.put(geMSSParameters58, num34);
        hashMap2.put(geMSSParameters60, num36);
        hashMap2.put(geMSSParameters62, num38);
        hashMap2.put(geMSSParameters64, num40);
        hashMap2.put(geMSSParameters66, num42);
        hashMap2.put(geMSSParameters68, num44);
        hashMap2.put(geMSSParameters70, num46);
        hashMap2.put(geMSSParameters72, num48);
        hashMap2.put(geMSSParameters74, num51);
        hashMap2.put(geMSSParameters75, num52);
    }

    private GeMSSParameters(String str, int i, int i2, int i3, int i4, int i5, int i6, int i7, int i8) {
        this.name = str;
        this.engine = new GeMSSEngine(i, i2, i3, i4, i5, i6, i7, i8);
    }

    public static Integer getID(GeMSSParameters geMSSParameters) {
        return paramsToOid.get(geMSSParameters);
    }

    public static GeMSSParameters getParams(Integer num) {
        return oidToParams.get(num);
    }

    public byte[] getEncoded() {
        return Pack.intToBigEndian(getID(this).intValue());
    }

    public GeMSSEngine getEngine() {
        return this.engine;
    }

    public String getName() {
        return this.name;
    }
}
